# Comment Here
name: CI + CD Development

on:
  push:
    branches: [ development ]
  workflow_dispatch:

anchors:
  runs_on: &runs_on
    ubuntu-latest
  
  checkout_code: &checkout_code
    uses: actions/checkout@v2
  
  build_code: &build_code
    name: Build Code
    run: echo Building some code...
  
  upload_artifacts: &upload_artifacts
    name: Upload Artifacts
    uses: actions/upload-artifact@v2
    with:
      name: cicd-environments
      if-no-files-found: error
      path: iac/
  
  download_artifacts: &download_artifacts
    name: Download Artifacts
    uses: actions/download-artifact@v2
    with:
      name: cicd-environments
      path: iac/
  
  azure_login: &azure_login
    name: Azure Login
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  pre_deployment_tasks: &pre_deployment_tasks
    name: Pre Deployment Tasks
    run: |
      echo "DATETIME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      echo "CURRENT_ENVIRONMENT_LOWER=${CURRENT_ENVIRONMENT,,}" >> $GITHUB_ENV
      echo I am deploying in ${{ env.CURRENT_ENVIRONMENT }}
      echo using template file ./iac/main.bicep
      echo using parameter file ./iac/parameters.${CURRENT_ENVIRONMENT,,}.json
  
  deploy_bicep_template: &deploy_bicep_template
    name: Deploy Bicep Template
    uses: azure/arm-deploy@v1
    with:
      subscriptionId: ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}
      deploymentName: ghactions-bicep-deploy-${{ env.DATETIME }}
      scope: resourcegroup
      resourceGroupName: ${{ secrets.RESOURCE_GROUP_NAME }}
      template: ./iac/main.bicep
      parameters: ./iac/parameters.${{ env.CURRENT_ENVIRONMENT_LOWER }}.json

jobs:
  Build:
    runs-on: *runs_on
    steps:
      - *checkout_code
      - *build_code
      - *upload_artifacts
  
  Development:
    name: Development
    environment: Development
    if: github.event.ref == 'refs/heads/development'
    needs: [Build]
    runs-on: *runs_on
    env:
      CURRENT_ENVIRONMENT: Development
    steps:
      - *download_artifacts
      - *azure_login
      - *pre_deployment_tasks
      - *deploy_bicep_template
