# Comment Here
name: CI + CD Development

on:
  push:
    branches: [ development ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo Hello, world!
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cicd-development
          if-no-files-found: error
          path: iac/
    
  DeployDevelopment:
    name: Deploy to Development
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Development
    env: 
      CURRENT_ENVIRONMENT: Development
      TEMPLATE_FILE: ./iac/main.bicep
      PARAMETERS_FILE: ./iac/parameters.development.json
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: cicd-development
          path: iac/
      
      - name: Deploy
        run: |
          echo I am deploying in ${{ env.CURRENT_ENVIRONMENT }}!
          echo using template file ${{ env.TEMPLATE_FILE }}
          echo using parameter file ${{ env.PARAMETERS_FILE }}
          echo contents of parameters file as follows:
          cat ${{ env.PARAMETERS_FILE }}
